### ISSUE TITLE
Kite stroke on ellipse1 test broken

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/kite#37]

**Comment by pixelzoom** [comment]
Insufficient info in this issue for me to evaluate it. Since it's labeled "bug" and the title says "broken", I'll err on the safe side and label it "Summer 2015 redeploy".

**Comment by jonathanolson** [comment]
Good excuse to tackle it! Turns out that Kite's stroking logic for line caps and line joins was assuming it was getting normalized tangent vectors, whereas Segment's startTangent/endTangent aren't normalized (they are dx/dt, dy/dt). Caused the line-cap on the elliptical arc to be significantly shortened (when Kite did the stroking with getStrokedShape()).

The proper normalization is now in place, although it probably wasn't causing any simulation issues.
