### ISSUE TITLE
Implement cardinal splines in Shape 

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/kite#45]
A sequence of Cardinal spline can be used to interpolate any number of points smoothly.
Unlike Bezier and b-splines, cardinal splines will necessarily go though the specified points. This 
Ultimately, it would be good to have support for a method that takes an array of points and output a shape that passes through all the points.

This paper: http://therndguy.com/papers/curves.pdf goes into some depth about the relation between the various splines. 

I need to implement a subset of this requirement for charges and fields but it would be more valuable if it lives in shape.

**Comment by bereaphysics** [comment]
Here is what I had in mind

````
    /**
     *
     * This is a convenience function that allows to generate Cardinal splines
     * from a position array. Cardinal spline differs from Bezier curves in that all
     * defined points on a Cardinal spline are on the path itself.
     *
     * It include a tension parameter to allow the client to specify how tightly
     * the path interpolates between points. One can think of the tension as the tension in
     * a rubber band around pegs. however unlike a rubber band the tension can be negative.
     * the tension ranges from -1 to 1.
     * @private
     * @param {Shape} shape
     * @param {Array.<Vector2>} positionArray
     * @param {Object} [options]
     * @returns {Shape}
     */
    positionArrayToCardinalSpline: function ( shape, positionArray, options ) {
      options = _.extend( {
        // the tension parameter controls how smoothly the curve turns through its
        // control points. For a Catmull-Rom curve the tension is zero.
        // the tension should range from -1 to 1
        tension: 0,

        // is the resulting shape forming a close path
        isClosedLineSegments: false,

      }, options );

      var cardinalPoints = []; // {Array.<Vector2>} cardinal points Array
      var bezierPoints = []; // {Array.<Vector2>} bezier points Array

      // if the line is open, there is one less segment than point vectors
      var segmentNumber = (options.isClosedLineSegments) ? positionArray.length : positionArray.length - 1;

      for ( var i = 0; i < segmentNumber; i++ ) {
        cardinalPoints = [];
        if ( i === 0 && !options.isClosedLineSegments ) {
          cardinalPoints.push(
            positionArray[ 0 ],
            positionArray[ 0 ],
            positionArray[ 1 ],
            positionArray[ 2 ] );
        }
        else if ( (i === segmentNumber - 1) && !options.isClosedLineSegments ) {
          cardinalPoints.push(
            positionArray[ i - 1 ],
            positionArray[ i ],
            positionArray[ i + 1 ],
            positionArray[ i + 1 ] );
        }
        else {
          cardinalPoints.push(
            positionArray[ (i - 1 + segmentNumber) % segmentNumber ],
            positionArray[ (i) % segmentNumber ],
            positionArray[ (i + 1 ) % segmentNumber ],
            positionArray[ (i + 2 ) % segmentNumber ] );
        }

        // Cardinal Spline to Cubic Bezier conversion matrix
        //    0                 1             0            0
        //  (-1+tension)/6      1      (1-tension)/6       0
        //    0            (1-tension)/6      1       (-1+tension)/6
        //    0                 0             1           0

        bezierPoints = [];
        bezierPoints.push( cardinalPoints[ 1 ] );
        bezierPoints.push( this.getWeightedVector( cardinalPoints[ 0 ], cardinalPoints[ 1 ], cardinalPoints[ 2 ], options ) );
        bezierPoints.push( this.getWeightedVector( cardinalPoints[ 3 ], cardinalPoints[ 2 ], cardinalPoints[ 1 ], options ) );
        bezierPoints.push( cardinalPoints[ 2 ] );

        shape.moveToPoint( bezierPoints[ 0 ] );
        shape.cubicCurveToPoint( bezierPoints[ 1 ], bezierPoints[ 2 ], bezierPoints[ 3 ] );
      }
      return shape;
    },
````

**Comment by jonathanolson** [comment]
Looks good. There are a few modifications I'd probably make to integrate it, do you mind if I add it to Kite?

**Comment by bereaphysics** [comment]
please go ahead

**Comment by samreid** [comment]
I wonder if this spline algorithm would work for energy skate park basics which also has the constraint that the spline must pass through the control points.  I believe right now energy skate park uses pairwise cubic splines: x=cubic1(t), y=cubic2(t)

**Comment by jonathanolson** [comment]
I've added an initial implementation, Shape's cardinalSpline().

I was expecting a smooth curve, but for my first test spline, there's a 90-degree turn between the bottom two cubics:

![screen shot 2015-05-12 at 12 32 27 am](https://cloud.githubusercontent.com/assets/480878/7581284/6e9129c8-f83e-11e4-8bb9-6a69f9bf72c4.png)

The cyan is the tangent at the end of each cubic segment, and the magenta circle indicates the curvature, and 0 tension was used.

Is this expected? I'm guessing not, because the control points are in a symmetric shape, but the resulting path isn't symmetric?

To reproduce, use:
```
var shape = new kite.Shape().cardinalSpline( [
  new Vector2( -100, -100 ),
  new Vector2( 100, -100 ),
  new Vector2( -100, 100 ),
  new Vector2( 100, 100 )
] );
```

Our control points for the three cubic curves are:
-100,-100 -66.66666666666667,-100 100,-133.33333333333331 100,-100
100,-100 100,-66.66666666666667 -66.66666666666667,100 -100,100
-100,100 -100,133.33333333333331 66.66666666666667,100 100,100

There seems to be a sharp bend between the 2nd and 3rd curves:
```js
s.subpaths[0].segments[1].getEndTangent()   // (-1,0)
s.subpaths[0].segments[2].getStartTangent() // (0,1)
```

I double-checked my modifications to the code by using your example above and modifying it to print out the cubic coordinates instead of modifying a shape, and got the following (which is identical):
-100,-100 -66.66666666666667,-100 100,-133.33333333333331 100,-100 
100,-100 100,-66.66666666666667 -66.66666666666667,100 -100,100 
-100,100 -100,133.33333333333331 66.66666666666667,100 100,100

@bereaphysics, can you check out the cardinalSpline() implementation in Shape, and see if there's something to be fixed? Or let me know if I should look into it.

**Comment by jonathanolson** [comment]
Also, if it helps, you can use Kite's playground.html, as it loads Kite and dependencies into the console. Uses kite.Shape and dot.Vector2.

I added the above shape to the visual-shape-test.html (which can be visited in the browser). By clicking the "spline" button (last Shape button), you'll be able to see what the path will end up like.

**Comment by jonathanolson** [comment]
Also, I changed a few things about the implementation. We don't move to each segment (since that was causing issues with strokes, since it was painting end caps where joins should be), and we don't force a new subpath at the start with a move (it works more like other equivalent operations, so you can do two different cardinal splines in a row, and if they start/end at the same point, it will use a line join nicely).

**Comment by bereaphysics** [comment]
Indeed this is not the correct behavior. 

It is fixed in the previous commit. Tension was set to zero

![image](https://cloud.githubusercontent.com/assets/7633344/7594041/4ac065e2-f89b-11e4-96ed-96ba2e788789.png)

and when setting isClosedLineSegments:true

![image](https://cloud.githubusercontent.com/assets/7633344/7594081/a2bd02be-f89b-11e4-9138-07fcdff1bea0.png)

There is still a problem with setting the tension to 1 (which is a pretty silly thing to do in this context since it is equivalent to just straight lines)

**Comment by bereaphysics** [comment]
Tension of 1 means that in  
````
        var bezierPoints = [
          cardinalPoints[ 1 ],
          weightedSplineVector( cardinalPoints[ 0 ], cardinalPoints[ 1 ], cardinalPoints[ 2 ], options.tension ),
          weightedSplineVector( cardinalPoints[ 3 ], cardinalPoints[ 2 ], cardinalPoints[ 1 ], options.tension ),
          cardinalPoints[ 2 ]
        ];

        // special operations on the first point
        if ( i === 0 ) {
          this.ensure( bezierPoints[ 0 ] );
          this.getLastSubpath().addPoint( bezierPoints[ 0 ] );
        }

        this.cubicCurveToPoint( bezierPoints[ 1 ], bezierPoints[ 2 ], bezierPoints[ 3 ] );
````

which gives becomes equivalent to 
        var bezierPoints = [
          cardinalPoints[ 1 ],
          cardinalPoints[ 1 ],
          cardinalPoints[ 2 ]
          cardinalPoints[ 2 ]
        ];
and then our starting point is bezierPoints[ 1 ] and we ask 

 this.cubicCurveToPoint( bezierPoints[ 1 ], bezierPoints[ 2 ], bezierPoints[ 2 ] );

this is just a straight line but kite balks at this point. 

It might be preferable to disallow tension=1, or to use a rule that when the client sets the tension to 1, then use internally,  tension=1 - epsilon

**Comment by bereaphysics** [comment]
any opinion @jonathanolson

**Comment by pixelzoom** [comment]
> It might be preferable to disallow tension=1, or to use a rule that when the client sets the tension to 1, then use internally, tension=1 - epsilon

+1 for disallowing `tension=1`, preferably via an assertion.  I don't like silently using `tension=1 - epsilon`, because that's not what the programmer specified.

**Comment by bereaphysics** [comment]
that sounds reasonable. I'll go ahead and implement it.

**Comment by jonathanolson** [comment]
Cubic is supposed to handle degenerate segments properly, I'd like to see why that is failing.

**Comment by jonathanolson** [comment]
Looks like there's an unimplemented bit in Cubic to handle that specific case, I'd like to fix that instead, and allow tension=1.

**Comment by bereaphysics** [comment]
did you see 
else if ( arePointsCollinear( start, control1, end ) && arePointsCollinear( start, control2, end ) ) {
        throw new Error( 'TODO, use extrema T funcs' );

**Comment by jonathanolson** [comment]
Yes, that's the part. The tricker part is if the points are visually collinear like the following:

control 1     start            end           control2.

Then you have to determine the extrema points on the curve, and draw lines from start => extrema 1 => extrema 2 => end.

**Comment by jonathanolson** [comment]
Ok, it should now work seamlessly for all tensions in range [-1,1]. Example splines in one Shape with rounded joins:

![kite-spline-closed](https://cloud.githubusercontent.com/assets/480878/7598894/fe0878a0-f8ba-11e4-8b6c-7ede80407c14.PNG)

If tension is 1 however, it turns into straight line segments, and thus will do mitered joins at each individual joint (whereas with tension < 1, it is a smooth curve and will have a smooth stroke).

Thanks for the implementation Martin! Assigning to you, in case there is something else to be done.

**Comment by bereaphysics** [comment]
I need to revert this last commit

**Comment by bereaphysics** [comment]
I fixed the documentation to state that tension=1 is allowed. Thanks @jonathanolson . Closing
