### ISSUE TITLE
rectangle with 2 rounded corners

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/kite#56]
From https://github.com/phetsims/sun/issues/197 ...

Add support (to Shape?) for creating a Shape that is a rectangle with 2 of its adjacent corners rounded, and the other 2 corners squared.

**Comment by jonathanolson** [comment]
As a more general pattern, can we supply a cornerRadius for each corner, OR boolean flags for which corners are rounded, and which ones aren't?

I'd hate to have to handle "rectangle with 1 or 3 rounded corners" separately.

Thoughts?

**Comment by samreid** [comment]
What if someone asks for a partially rounded triangle?

**Comment by pixelzoom** [comment]
> What if someone asks for a partially rounded triangle?

Then they have a blank slate to write their own, because there is no scenery.Triangle, and I don't see any triangle functions in kite.Shape.

**Comment by pixelzoom** [comment]
>  can we supply a cornerRadius for each corner,

Since the most common use case is to have the same radius for all rounded corners, this duplicates the problem that we have with scenery.Rectangle (https://github.com/phetsims/scenery/issues/467).

> OR boolean flags for which corners are rounded, and which ones aren't?

OK with me.

**Comment by jonathanolson** [comment]
Any preferences between reusing Shape.roundedRectangle or a new function, and also between optional arguments for corners:
```js
function( x, y, width, height, arcw, arch, isUpperLeftSharp, isUpperRightSharp, isLowerRightSharp, isLowerLeftSharp )
```
or more of an options pattern:
```js
function( x, y, width, height, { cornerRadius: ..., roundUpperLeft: false, ... } )
```
or any other combination?

**Comment by jonathanolson** [comment]
Marked for developer-meeting as an API question.

**Comment by pixelzoom** [comment]
9/24/15 dev meeting:

```js
// function signature
Shape.roundedRectangleWithRadii =  function( x, y, width, height, {
topLeftCornerRadius:
topRightCornerRadius: 
bottomLeftCornerRadius:
bottomRightCornerRadius: 
} ) { ... };

// use case
var cornerRadius = 20;
var rect = Shape.roundedRectangleWithRadii( 0, 0, 200, 100, {
topLeftCornerRadius: cornerRadius,
topRightCornerRadius: cornerRadius
} );
```

**Comment by jonathanolson** [comment]
Completed, assigning for review, and to consider not including "CornerRadius" in every corner option. Any opinion on:
```js
// use case
var cornerRadius = 20;
var rect = Shape.roundedRectangleWithRadii( 0, 0, 200, 100, {
  topLeft: cornerRadius,
  topRight: cornerRadius
} );
```

**Comment by pixelzoom** [comment]
I guess the only reason to include "CornerRadius" in each option name would be if we think there will additional options. If we don't think there will be additional options, then I recommend renaming the `options` parameter to `cornerRadii`.   Any other opinions?...

**Comment by pixelzoom** [comment]
Since `Shape.roundedRectangleWithRadii` is unlikely to be used for other types of rectangles, I think it's appropriate to change its signature to:

`Shape.roundedRectangleWithRadii( x, y, width, height, cornerRadii )`

where `cornerRadii` defaults to:

```js
{
  topLeft: 0,
  topRight: 0,
  bottomLeft: 0,
  bottomRight: 0
}
```

**Comment by samreid** [comment]
The suggestion in https://github.com/phetsims/kite/issues/56#issuecomment-143797019 seems good to me.

**Comment by jbphet** [comment]
+1 for https://github.com/phetsims/kite/issues/56#issuecomment-143797019.

**Comment by jonathanolson** [comment]
Changed, assigning @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.

**Comment by jbphet** [comment]
Reopening - I believe the convention in other PhET libraries is to specify 2D options with the x value first and the y value second, e.g. leftTop instead of topLeft (see Node.js in Scenery).  Shouldn't we follow the same convention here?

**Comment by pixelzoom** [comment]
OK with me. Back to @jonathanolson.

**Comment by samreid** [comment]
Yes, same convention please.

**Comment by samreid** [comment]
We will take this next step in a new issue https://github.com/phetsims/kite/issues/106, closing.
