### ISSUE TITLE
bring documentation up to PhET standards

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/kite#58]
6/16/16 dev meeting: Decided to create this issue, as a first step towards improving knowledge sharing. 

@ariel-phet asked me to do this sometime after Function Builder 1.0.0 is published.

**Comment by pixelzoom** [comment]
Taking a quick look through kite source...  

Methinks that we'll need to have a dev discussion about:

(1) How to document options. I prefer to document them next to their default values in the `_.extend` call, @jonathanolson seems to document them elsewhere (usually in the function comment?)

(2) How to document duck typing. For example, suppose that I see parameter `v`, and it looks to be a vector. Then I read through the source and see that it can be anything with `x` and `y` properties. How should I document this parameter?  Both of these are technically correct:

`@param {{x: number, y: number}} v`
`@param {Vector2|{x: number, y: number}} v`

**Comment by pixelzoom** [comment]
The other thing that's going to be difficult is guessing what the intended visibility is for functions and properties. Visibility annotations are used inconsistently - sometimes present, something totally absent. Does their absence imply `@public`?  It would be very helpful to get direction from @jonathanolson on this.

**Comment by jonathanolson** [comment]
Annotations issue noted in https://github.com/phetsims/kite/issues/52, I'll definitely want to be the one to note those.

Re (1), I don't have a strong preference, but I'd generally like options to be documented in one place, then have "see X" elsewhere. Options in certain styles (e.g. Scenery) use mutate(), so there is no _.extend. It also depends on whether there are setters or not.

Re (2), for Kite, it's almost always going to be typed as just Vector2 (with assertions in place in the future), so that Kite has the flexibility to use Vector2 methods.

**Comment by pixelzoom** [comment]
6/23/16 dev meeting:  I'm unlikely to get to this until after @jonathanolson returns from leave. And if I flesh out the documentation, I'll be guessing at some (much?) of it.  It will be more efficient and accurate if @jonathanolson handles this when he returns.  So assigning it to him.

**Comment by veillette** [comment]
I was able to put visibility annotations in Shape, but for the other modules, it wasn't clear, So i didn't put any annotations. In any case this is tracked in #52.

There are a few methods I was not able to document

In Arc.js
- [ ] getActualEndAngle
- [ ] includeBoundsAtAngle
- [ ] containsAngle
- [ ] intersection

in Cubic.js
 Most of it was too arcane. Much remains to do

in EllipticalArc.js
- [ ] getUnitTransform
- [ ] getActualEndAngle
- [ ] getUnitArcSegment
- [ ] includeBoundsAtAngle
- [ ] containsAngle
- [ ] intersection

in Line.js
- [ ] intersection

in Quadratic.js
- [ ] getTCriticalX
- [ ] getTCriticalY
- [ ] approximateOffset 
- [ ] getInteriorExtremaTs
- [ ] insersection
- [ ] extremaT

in Segment.js
- [ ] subdivisions
- [ ] subdividedIntoMonotone
- [ ] getBoundsWithTransform

in Subpath.js
- [ ] transformed
- [ ] nonlinearTransformed
- [ ] toPiecewiseLinear
- [ ] invalidatePOints
- [ ] invalidate

in Shape.js
- [ ] intersection
- [ ] containsPoint
- [ ] getOffsetShape
- [ ] getStrokedBounds
- [ ] getBounds
- [ ] getBoundsWithTransform
- [ ] toString
- [ ] ensure
- [ ] addSegmentsAndBounds

**Comment by samreid** [comment]
This has been "top priority" for more than a year.  Is the priority label still accurate?  If so, is this problem getting the attention it needs?

**Comment by jonathanolson** [comment]
Just ran through and handled documentation to bring things up-to-standard. Every function should now have visibility/args/description/etc.
