### ISSUE TITLE
Shape doesn't properly document optional parameters

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/kite#62]
Shape doesn't properly document which parameters are optional. For example, for `arc`:

``` js
    /**
     * @public
     * @param {number} centerX - horizontal coordinate of the center of the arc
     * @param {number} centerY - Center of the arc
     * @param {number} radius - How far from the center the arc will be
     * @param {number} startAngle - Angle (radians) of the start of the arc
     * @param {number} endAngle - Angle (radians) of the end of the arc
     * @param {boolean} anticlockwise - Decides which direction the arc takes around the center
     * @returns {Shape}
     **/
    arc: function( centerX, centerY, radius, startAngle, endAngle, anticlockwise ) {
```

The `anticlockwise` parameter is optional, and should have square brackets around the parameter name, to indicate that it's optional:

``` js
     * @param {boolean} [anticlockwise] - Decides which direction the arc takes around the center
```

IntelliJ IDEA has gotten smarter, and is now flagging this as a problem.  E.g. for a call to `Shape.arc` in WavelengthSlider, it's complaining that the `anticlockwise` arg is missing:

![screenshot_88](https://cloud.githubusercontent.com/assets/3046552/17912501/4cd20ade-6951-11e6-944e-e93650ebb95f.png)

**Comment by pixelzoom** [comment]
I handled this for `[anticlockwise]`, but I'm unsure if there are other such parameters in Shape. Assigning to @jonathanolson to review and correct any additional documentation errors.

**Comment by jonathanolson** [comment]
Looks good! Scanned for similar issues and didn't see anything. Closing.
