### ISSUE TITLE
regression tests are broken

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/kite#63]
kite @733028991124bcea81c36b315f00e18453ba3d7b

http://localhost/~cmalley/GitHub/kite/tests/qunit/compiled-unit-tests.html

0 assertions of 35 passed, 35 failed.

![screenshot_18](https://cloud.githubusercontent.com/assets/3046552/18569243/a10f78ec-7b5e-11e6-9ec7-2c17b20c0f87.png)

**Comment by samreid** [comment]
It looks like you are running the compiled unit tests.  Did you build kite first?

Here's the requirejs unit tests: http://localhost/kite/tests/qunit/unit-tests.html

**Comment by samreid** [comment]
Build is failing, I'm not sure why:

Running "requirejs:development" (requirejs) task
>> Error: TypeError: Cannot read property 'chipper' of undefined
>> In module tree:
>>     AXON/main
>>       AXON/Property
>>         ifphetio
>> 
>>     at Object.load (eval at <anonymous> (/Users/samreid/github/kite/node_modules/requirejs/bin/r.js:28057:38), <anonymous>:31:25)
Warning: Task "requirejs:development" failed. Use --force to continue.

Aborted due to warnings.

**Comment by samreid** [comment]
Fixed build above, now I'm seeing tests pass for built and requirejs modes.  @pixelzoom can you review?

**Comment by pixelzoom** [comment]
I navigated to http://localhost/~cmalley/GitHub/kite/, was presented with a webpage, and (silly me) thought that pressing the "Test" button would be useful.  

Kite now building, tests passing.

Assigning to @jonathanolson to put some useful information in kite/tests/README.md.

**Comment by jonathanolson** [comment]
Added notes that compiled tests require building first, and updated build instructions for 'grunt build-js'
