### ISSUE TITLE
use self for closure variable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/kite#64]
After discussion at 9/15/16 developer meeting, PhET has standardized on the name used for the closure variable whose value is `this`:

```var self = this;```

Please update this repository accordingly.  Looks like only 4 occurrences, so should be pretty quick. I'd do it myself, but the regression tests are currently in a broken state (https://github.com/phetsims/kite/issues/63).

**Comment by samreid** [comment]
Fixed above and unit tests are passing, and grunt is passing.

![image](https://cloud.githubusercontent.com/assets/679486/18569565/9f1449bc-7b60-11e6-9ced-932f9cc91f38.png)

@pixelzoom do you want to review?
