### ISSUE TITLE
parseFloat called with radix argument

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/kite#68]
`parseFloat` is used in svgPath.js with a radix argument, i.e.:

```js
2093 result0 = (function( offset, number ) { return parseFloat( number, 10 ); })( pos0, result0 );

2134 result0 = (function( offset, sign, number ) { return parseFloat( sign + number, 10 ); })( pos0, result0[ 0 ], result0[ 1 ] );
```

`parseFloat` does not have a radix parameter, someone is confusing it with `parseInt`.

svgPath.js looks like generated code, so perhaps we shouldn't worry about it.  But I'm not familiar with what the thing that generated it ("Generated by PEG.js 0.7.0.") or how it was generated.

@jonathanolson your call.

**Comment by jonathanolson** [comment]
Fixed and made it a multi-line comment for increased visibility. Look good?

**Comment by pixelzoom** [comment]
👍 Closing.
