### ISSUE TITLE
Add Shape.zigZagTo

### ISSUE THREAD

**Issue by samreid** [phetsims/kite#75]
I added zig-zag code for the filament for the fuse in Circuit Construction Kit, in https://github.com/phetsims/circuit-construction-kit-common/issues/479 and https://github.com/phetsims/circuit-construction-kit-common/issues/469.

![image](https://user-images.githubusercontent.com/679486/56511167-260c2b00-64e9-11e9-8d0b-cf567272436b.png)

I asked on Slack if the zig-zag code should be moved to common code, general agreement was that it should be moved.  We also identified several other places with zig-zagging code:

* Faraday's Law Light bulb filament
* Capacitor Lab Basics light bulb filament
* ExpressionNode

Here's the full conversation for archival purposes:

```
Sam Reid [10:07 AM]
I added a zig zag shape command for CCK.  I’m wondering if it should remain in CCK or be moved to Shape.js.
https://github.com/phetsims/circuit-construction-kit-common/blob/1c809c55b6e27491b896efe77c53505a6a05379d/js/view/zigZag.js
Pasted image at 2019-04-22, 10:07 AM 



Michael Kauzmann [10:17 AM]
My vote would be to move to Shape.js

Jesse Greenberg [10:18 AM]
Could be useful for other sims with circuits, faradays-law also has a zig zag

Sam Reid [10:22 AM]
Thanks, I see the FL zig-zag code now.  I’m also seeing something similar in ExpressionNode and capacitor lab basics bulb filament.

Jonathan Olson [10:22 AM]
I'm fine with it in Shape.js
it seems atypical for methods on a Shape to include the start point (since it already has that information)
what do you think of if it was moveTo( ... ).zigZagTo( ... ) where the zig-zag didn't include the start?

Sam Reid [10:23 AM]
That seems right to me
```

**Comment by samreid** [comment]
I moved this implementation from Circuit Construction Kit Common, and ported CCK to use it.  I opened new issues for code that looks like it should use this new implementation.  @jonathanolson can you please review?

**Comment by Denz1994** [comment]
@samreid Sims that require a symmetrical zig zag don't get drawn properly (see https://github.com/phetsims/capacitor-lab-basics/issues/258#issuecomment-486489352 and https://github.com/phetsims/faradays-law/issues/153#issuecomment-487789685). 

I added a flag to determine which drawing pattern to use ( asymmetrical/symmetrical). It seems a bit hackish to have two drawing patterns in the same function, so your input on fixing this bug would be helpful.

**Comment by veillette** [comment]
The previous commit handles zig-zags for no-vertical orientation using the same API. Assigning to @jonathanolson  to review.

**Comment by samreid** [comment]
Unassigning since @jonathanolson is requested for review, but let me know if I should be reassigned.

**Comment by jonathanolson** [comment]
Looks good to me!

**Comment by samreid** [comment]
Thanks @jonathanolson.  This issue seems good and ready to close, but note there is still outstanding work to be done in https://github.com/phetsims/faradays-law/issues/153#issuecomment-498742921
