### ISSUE TITLE
LineStyles uses _.extend instead of PHET_CORE/merge

### ISSUE THREAD

**Issue by zepumph** [phetsims/kite#81]
From https://github.com/phetsims/phet-core/issues/71, this is because there is a usage of the type which passes in a constructed object (with a non-`Object` prototype) as options. With `PHET_CORE/merge` this is no longer allowed. @jonathanolson how would you like to proceed here?

**Comment by jonathanolson** [comment]
Added LineStyles.copy() and using it, so we can use merge. Implemented above.
