### ISSUE TITLE
Import kite files from `imports.js`

### ISSUE THREAD

**Issue by zepumph** [phetsims/kite#96]
I added a lint rule to mimic the scenery one about importing from imports, instead of directly, and then I found myself needing to change thousands of files. Commits coming up! Tagging @jonathanolson 

Lint rule added in https://github.com/phetsims/chipper/commit/1e6e531b35ab3759da04ed5e42f04a2180b0e589.

**Comment by zepumph** [comment]
@jonathanolson, let me know if I should have done anything different, sorry I sorta fell into doing this work because I committed and pushed the lint rule too quickly. Feel free to close.

**Comment by jonathanolson** [comment]
Looks good!
